version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: nginx
    container_name: nginx
    ports:
      - 443:443

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data

  express:
    build:
      context: ./express
      dockerfile: Dockerfile.dev
    image: express
    container_name: express
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./express:/usr/src/app
      - express_node_modules:/usr/src/app/node_modules
    ports:
      - '5000:5000'

volumes:
  express_node_modules:
  redis_data:

  # wetty-for-build-only:
  #   build:
  #     context: .
  #     dockerfile: ./docker/wetty/Dockerfile.dev
  #   image: wetty
  #   container_name: wetty1
  #   entrypoint: ['ls']
  #   ports:
  #     - 8888:3000
