version: '3.9'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.dev
    image: nginx
    container_name: nginx
    ports:
      - 443:443

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile.dev
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'

  express:
    build:
      context: .
      dockerfile: ./docker/express/Dockerfile.dev
    image: express
    container_name: express
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app
      - express_node_modules:/usr/src/app
    ports:
      - '5000:5000'

volumes:
  express_node_modules:

  # wetty-for-build-only:
  #   build:
  #     context: .
  #     dockerfile: ./docker/wetty/Dockerfile.dev
  #   image: wetty
  #   container_name: wetty1
  #   entrypoint: ['ls']
  #   ports:
  #     - 8888:3000
