version: "3.9"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - 443:443

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    container_name: redis
    volumes:
      - redis_data:/data

  express:
    build:
      context: ./express
      dockerfile: Dockerfile.dev
    container_name: express
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./express:/usr/src/app
      - express_node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  express_node_modules:
  redis_data:
